// Generated by CoffeeScript 1.9.2
(function() {
  var app, bodyParser, express, indexController, port, server;

  express = require('express');

  bodyParser = require('body-parser');

  indexController = require('./controllers/index.js');

  app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express["static"](__dirname + '/public'));

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.get('/', indexController.index);

  app.get('/templates/:templateid', function(req, res) {
    return res.render('templates/' + req.params.templateid);
  });

  port = process.env.PORT || 3001;

  server = app.listen(port, function() {
    return console.log("Express server listening on port " + (server.address().port));
  });

}).call(this);
