// Generated by CoffeeScript 1.9.2
(function() {
  describe('directives', function() {
    var $compile, $rootScope;
    $compile = void 0;
    $rootScope = void 0;
    beforeEach(module("app"));
    beforeEach(inject(function(_$compile_, $_rootScope_) {
      $compile = $_compile_;
      return $rootScope = $_rootScope_;
    }));
    return it('should return the correct views', function() {
      var element;
      element = $compile('<options-list></options-list>');
      $rootScope.$digest();
      return expect(element.html()).toContain('The List');
    });
  });
}).call(this);
